#' Plot Half Violin with Thresholds (roxygen documentation generated by ChatGPT)
#'
#' This function creates a plot with half-violin density ridges, means with error bars,
#' threshold lines, and text labels for percentage values.
#'
#' @param data A data frame containing the input data.
#' @param x_var A variable specifying the x-axis values.
#' @param y_var A variable specifying the y-axis values.
#' @param fill_var A variable specifying the fill colors.
#' @param dodge_width The width for dodging the position of the means (default is 0.8).
#' @param color_palette A vector specifying the color palette for fills and colors (default is cbbPalette).
#' @param facetformula_var A formula specifying the facets for the plot.
#' @param facet_strvar A variable specifying the facet strings.
#' @param title_var A string specifying the title of the plot.
#' @param thres_var A variable specifying the threshold values.
#' @param perc_var A variable specifying the percentage values.
#' @param perclabelx A numeric value specifying the x-position for percentage labels (default is 1).
#' @param facet_var A variable specifying additional facets for the plot.
#' @param labelsize An integer specifying the size of the text labels (default is 6).
#' @param basesize_var An integer specifying the base size for theme settings (default is 18).
#'
#' @return A ggplot object representing the plot with half-violin density ridges, means with error bars,
#' threshold lines, and text labels for percentage values.
#' @export
#'
#' @import ggplot2
#' @import ggridges
#' @import dplyr

plothalfviolin_withthres <- function(data, x_var, y_var, fill_var, dodge_width = 0.8, color_palette = cbbPalette, facetformula_var, facet_strvar, title_var, thres_var, perc_var, perclabelx = 1, facet_var, labelsize = 6, basesize_var = 18 ) {

      thresdf <- dplyr::select( data, {{y_var}}, {{thres_var}} ) %>%
            unique()

      labeldf <- dplyr::select( data, {{y_var}}, all_of(c(facet_strvar)), {{perc_var}} ) %>%
            unique()

      plotout <- ggplot() +
            ggridges::geom_density_ridges(data = data, aes(y = {{ y_var }}, x = {{ x_var }}, fill = {{ fill_var }}), alpha = 0.2) +
            stat_summary(data = data, aes(y = {{ y_var }}, x = {{ x_var }}), fun = 'mean',
                         fun.max = function(x) { quantile(x, 0.25) },
                         fun.min = function(x) { quantile(x, 0.75) },
                         geom = "pointrange", show.legend = FALSE, position = position_dodge(width = dodge_width)) +
            geom_vline( data = thresdf, aes( xintercept = {{thres_var}}, color = {{fill_var}}), linetype = 'dashed' ) +
            geom_text( data = labeldf, aes( x = perclabelx, y = {{y_var}}, label= {{perc_var}} ), size = labelsize ) +
            scale_fill_manual(values = color_palette) +
            scale_color_manual(values = color_palette) +
            facet_grid(as.formula(facetformula_var)) +
            theme_bw(base_size = basesize_var) +
            theme(axis.text.x = element_text(angle = 90)) +
            # coord_flip() +
            ggtitle( title_var )

      return(plotout)
}
